# Generated by Django 5.1.1 on 2024-11-04 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_additional_image'),
        ('teams', '0006_alter_team_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
        migrations.AddField(
            model_name='report',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.teammember'),
        ),
        migrations.AddField(
            model_name='report',
            name='job_issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
