# Generated by Django 5.1.1 on 2024-09-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='comapany',
            new_name='company',
        ),
    ]
